### ISSUE TITLE
examples/iron-router : TypeError: Object #<Object> has no method 'Paginate'

### ISSUE THREAD

**Issue by lc3t35** [alethes/meteor-pages#115]
Trying to have examples/iron-router working with meteor version 1.0.2 instead of 0.6.
Changed packages file in .meteor, remove others not needed files
````
meteor-platform
insecure
coffeescript
iron:router
ian:bootstrap-3
alethes:pages
````
Update and verify 
````
meteor update
This project is already at Meteor 1.0.2.1, the latest release.                                          
Changes to your project's package version selections from updating package versions:                        
alethes:pages              added, version 1.7.2
application-configuration  added, version 1.0.4
autoupdate                 added, version 1.1.4
base64                     added, version 1.0.2
binary-heap                added, version 1.0.2
blaze                      added, version 2.0.4
blaze-tools                added, version 1.0.2
boilerplate-generator      added, version 1.0.2
callback-hook              added, version 1.0.2
check                      added, version 1.0.3
coffeescript               added, version 1.0.5
ddp                        added, version 1.0.13
deps                       added, version 1.0.6
ejson                      added, version 1.0.5
fastclick                  added, version 1.0.2
follower-livedata          added, version 1.0.3
geojson-utils              added, version 1.0.2
html-tools                 added, version 1.0.3
htmljs                     added, version 1.0.3
http                       added, version 1.0.9
ian:bootstrap-3            added, version 3.3.1
id-map                     added, version 1.0.2
insecure                   added, version 1.0.2
iron:controller            added, version 1.0.6
iron:core                  added, version 1.0.6
iron:dynamic-template      added, version 1.0.6
iron:layout                added, version 1.0.6
iron:location              added, version 1.0.6
iron:middleware-stack      added, version 1.0.6
iron:router                added, version 1.0.6
iron:url                   added, version 1.0.6
jquery                     added, version 1.0.2
json                       added, version 1.0.2
launch-screen              added, version 1.0.1
livedata                   added, version 1.0.12
logging                    added, version 1.0.6
meteor                     added, version 1.1.4
meteor-platform            added, version 1.2.1
minifiers                  added, version 1.1.3
minimongo                  added, version 1.0.6
mobile-status-bar          added, version 1.0.2
mongo                      added, version 1.0.11
observe-sequence           added, version 1.0.4
ordered-dict               added, version 1.0.2
random                     added, version 1.0.2
reactive-dict              added, version 1.0.5
reactive-var               added, version 1.0.4
reload                     added, version 1.1.2
retry                      added, version 1.0.2
routepolicy                added, version 1.0.3
session                    added, version 1.0.5
spacebars                  added, version 1.0.4
spacebars-compiler         added, version 1.0.4
templating                 added, version 1.0.10
tracker                    added, version 1.0.4
ui                         added, version 1.0.5
underscore                 added, version 1.0.2
url                        added, version 1.0.3
webapp                     added, version 1.1.5
webapp-hashing             added, version 1.0.2

pc10:iron-router laurent$ meteor list         
alethes:pages    1.7.2  State of the art, out of the box Meteor pagination
coffeescript     1.0.5  Javascript dialect with fewer braces and semicolons
ian:bootstrap-3  3.3.1  HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.
insecure         1.0.2  Allow all database writes by default
iron:router      1.0.6  Routing specifically designed for Meteor
meteor-platform  1.2.1  Include a standard set of Meteor packages in your app
````
Run and fail 
````
meteor              
[[[[[ ~/dev/meteor/meteor-pages/examples/iron-router ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
W20150111-00:10:17.474(1)? (STDERR)           
W20150111-00:10:17.555(1)? (STDERR) /Users/laurent/.meteor/packages/meteor-tool/.1.0.38.txrqxd++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150111-00:10:17.556(1)? (STDERR) 						throw(ex);
W20150111-00:10:17.556(1)? (STDERR) 						      ^
W20150111-00:10:17.556(1)? (STDERR) TypeError: Object #<Object> has no method 'Paginate'
W20150111-00:10:17.557(1)? (STDERR)     at ./app.coffee:5:17
W20150111-00:10:17.557(1)? (STDERR)     at ./app.coffee:1:1
W20150111-00:10:17.557(1)? (STDERR)     at /Users/laurent/dev/meteor/meteor-pages/examples/iron-router/.meteor/local/build/programs/server/boot.js:175:10
W20150111-00:10:17.557(1)? (STDERR)     at Array.forEach (native)
W20150111-00:10:17.557(1)? (STDERR)     at Function._.each._.forEach (/Users/laurent/.meteor/packages/meteor-tool/.1.0.38.txrqxd++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150111-00:10:17.558(1)? (STDERR)     at /Users/laurent/dev/meteor/meteor-pages/examples/iron-router/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
W20150111-00:10:19.624(1)? (STDERR)           
W20150111-00:10:19.626(1)? (STDERR) /Users/laurent/.meteor/packages/meteor-tool/.1.0.38.txrqxd++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150111-00:10:19.627(1)? (STDERR) 						throw(ex);
W20150111-00:10:19.627(1)? (STDERR) 						      ^
W20150111-00:10:19.628(1)? (STDERR) TypeError: Object #<Object> has no method 'Paginate'
W20150111-00:10:19.628(1)? (STDERR)     at ./app.coffee:5:17
W20150111-00:10:19.629(1)? (STDERR)     at ./app.coffee:1:1
W20150111-00:10:19.629(1)? (STDERR)     at /Users/laurent/dev/meteor/meteor-pages/examples/iron-router/.meteor/local/build/programs/server/boot.js:175:10
W20150111-00:10:19.629(1)? (STDERR)     at Array.forEach (native)
W20150111-00:10:19.629(1)? (STDERR)     at Function._.each._.forEach (/Users/laurent/.meteor/packages/meteor-tool/.1.0.38.txrqxd++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20150111-00:10:19.630(1)? (STDERR)     at /Users/laurent/dev/meteor/meteor-pages/examples/iron-router/.meteor/local/build/programs/server/boot.js:86:5
=> Exited with code: 8
^C                        
````

**Comment by alethes** [comment]
The iron-router example should be working fine with Meteor 1.0+. It seems you're using the outdated example code. The current version uses Meteor 1.0.3.1. Please clone the most recent version of the repository and try again.

**Comment by lc3t35** [comment]
Done (oops ! my fork was not in sync ;). Working fine now. Thank you.
