### ISSUE TITLE
Error when setting `router: 'true'` as per docs.

### ISSUE THREAD

**Issue by nicksergeant** [alethes/meteor-pages#132]
```
Exception in template helper: TypeError: Cannot read property 'path' of undefined
    at Pages.__Pages.Pages.linkTo (http://localhost:3000/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:543:53)
    at Object.Template._pagesNav.helpers.link (http://localhost:3000/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:1451:19)
    at bindDataContext (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2727:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1606:16)
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:171:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:108:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7f53771c84a2eafac2b561c9796dda0d8af8e7f5:112:39)
    at Template._pagesNav.Blaze.If.HTML.DIV.HTML.UL.Blaze.Each.HTML.LI.HTML.A.href (http://localhost:3000/packages/alethes_pages.js?c34e40f7b75aeda63059eaf986e5f32eddb1b152:1289:28)
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12)
    at Blaze._HTMLJSExpander.def.visitAttribute (http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1971:21)
```

This is after setting the following:

```
ItemsPaged = new Meteor.Pagination(Items, {
  availableSettings: {
    filters: true
  },
  onReloadPage1: true,
  itemTemplate: 'ItemDetail',
  navShowFirst: false,
  navShowLast: false,
  router: 'true',
  perPage: 10,
  sort: {
    pubDate: -1
  },
});
```

The docs seem to indicate to set `router` to 'true' as a string:

> router (String, default = **undefined)**

If I set to `true`, the server crashes:

```
W20150323-01:30:51.618(-4)? (STDERR) /Users/Nick/.meteor/packages/meteor-tool/.1.0.41.wyca8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:173
W20150323-01:30:51.618(-4)? (STDERR)                                            throw(ex);
W20150323-01:30:51.618(-4)? (STDERR)                                                  ^
W20150323-01:30:51.654(-4)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20150323-01:30:51.654(-4)? (STDERR)     at checkSubtree (packages/check/match.js:244:1)
W20150323-01:30:51.654(-4)? (STDERR)     at check (packages/check/match.js:32:1)
W20150323-01:30:51.654(-4)? (STDERR)     at Pages.__Pages.Pages._set (packages/alethes:pages/lib/pages.coffee:312:9)
W20150323-01:30:51.654(-4)? (STDERR)     at Pages.__Pages.Pages.set (packages/alethes:pages/lib/pages.coffee:246:20)
W20150323-01:30:51.655(-4)? (STDERR)     at Pages.__Pages.Pages.setInitial (packages/alethes:pages/lib/pages.coffee:275:6)
W20150323-01:30:51.655(-4)? (STDERR)     at new Pages (packages/alethes:pages/lib/pages.coffee:112:6)
W20150323-01:30:51.655(-4)? (STDERR)     at lib/items.es6.js:3:14
W20150323-01:30:51.655(-4)? (STDERR)     at /Users/Nick/Code/siftie/.meteor/local/build/programs/server/app/lib/items.es6.js.js:17:3
W20150323-01:30:51.655(-4)? (STDERR)     at /Users/Nick/Code/siftie/.meteor/local/build/programs/server/boot.js:205:10
W20150323-01:30:51.655(-4)? (STDERR)     at Array.forEach (native)
```

**Comment by vnenkpet** [comment]
Also running into this problem... no info?

**Comment by gabrielstuff** [comment]
Same here. Did not find anything... Using iron-router internally.

**Comment by olivierpascal** [comment]
Same problem here.

**Comment by jogster** [comment]
It is a string, so use the value "true", "false".....

From docs:
router (String, default = **undefined)** - Three options:
true - a router is used but the routes are configured separately by the user
false - no router used
"iron-router" - iron-router is used and the routes are automatically set up by Pages

**Comment by jogster** [comment]
Unless you are creating a single page application the router (in this case iron router) is irrelevant. By default the router is set as undefined. Just leave the option out and (e.g. router) and then the implementation does not try and hook up to the router.

As a result the exception is not hit.
