### ISSUE TITLE
Unable to add meteor-pages package to my project.

### ISSUE THREAD

**Issue by gauravraj** [alethes/meteor-pages#206]
As soon as I add this package to my project I get the following errors - 
ReferenceError: Items is not defined
W20160420-12:15:21.121(5.5)? (STDERR)     at __coffeescriptShare (packages/alethes_pages/examples/basic/main.coffee:2:32)
W20160420-12:15:21.121(5.5)? (STDERR)     at packages/alethes_pages/examples/basic/main.coffee:2:1
W20160420-12:15:21.121(5.5)? (STDERR)     at /home/neelesh/Development/pictorwebserver/.meteor/local/build/programs/server/packages/alethes_pages.js:2781:3
W20160420-12:15:21.121(5.5)? (STDERR)     at /home/neelesh/Development/pictorwebserver/.meteor/local/build/programs/server/boot.js:242:10
W20160420-12:15:21.121(5.5)? (STDERR)     at Array.forEach (native)
W20160420-12:15:21.121(5.5)? (STDERR)     at Function._.each._.forEach (/home/neelesh/.meteor/packages/meteor-tool/.1.1.9.1py39b4++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160420-12:15:21.122(5.5)? (STDERR)     at /home/neelesh/Development/pictorwebserver/.meteor/local/build/programs/server/boot.js:137:5

**Comment by arist0tl3** [comment]
+1

**Comment by air-cc** [comment]
+1 why the directory of examples in the package?

**Comment by ddela-cr** [comment]
+1

**Comment by anthonyserious** [comment]
+1

**Comment by stefankutko** [comment]
+1

**Comment by andrewpmckenzie** [comment]
+1

**Comment by kyv** [comment]
+1

**Comment by JTL1992** [comment]
+1
